#include <iostream>
#include <fstream>
#include <vector>
#include <string>
#include "qat_unet_model.h" // Your model loading code
#include "kernels.h"        // Where attention_block is

// Helper to load a flat vector into a Tensor
Tensor load_tensor_from_file(const std::string& path, const std::vector<size_t>& shape) {
    std::ifstream file(path);
    std::vector<float> data;
    float val;
    while (file >> val) {
        data.push_back(val);
    }
    Tensor t(shape);
    if (data.size() != t.numel()) {
        throw std::runtime_error("Loaded data size mismatch with target tensor shape.");
    }
    t.data = data;
    return t;
}

// Helper to save a tensor for comparison
void save_tensor_to_file(const Tensor& t, const std::string& path) {
    std::ofstream file(path);
    // No need for t.contiguous() as Tensor is already a flat vector internally
    for (const auto& val : t.data) {
        file << std::setprecision(20) << val << std::endl;
    }
}

int main() {
    // 1. Load the full model to get the attention block layer weights
    QATUNetModel model;
    // Ensure 'qat_unet_model_packed.bin' is in the correct directory (e.g., build/bin)
    // relative to where the executable will be run.
    model.load_model("qat_unet_model_packed.bin"); 

    // 2. Load the input tensor generated by Python
    // Use the exact shape from the Python script's output (e.g., golden_test.py output or sample input for attention)
    // This example uses a placeholder shape; you must replace it with the correct shape.
    Tensor input_tensor = load_tensor_from_file("attention_input.txt", {1, 256, 16, 16}); // **ADJUST THIS SHAPE**

    // 3. Run the C++ attention_block function
    Tensor output_tensor_cpp = attention_block(input_tensor, *model.middle_block1->attention);

    // 4. Save the C++ output
    save_tensor_to_file(output_tensor_cpp, "attention_output_cpp.txt");

    std::cout << "C++ attention block output saved to attention_output_cpp.txt" << std::endl;
    std::cout << "Now, compare this file with attention_output_python.txt" << std::endl;

    return 0;
}